" bclindner vimrc

" vim-plug configuration
call plug#begin('~/.vim/plugged/')
"" THE ESSENTIALS - statusline, file tree, linter, fuzzy finder.
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'w0rp/ale'
Plug 'ctrlpvim/ctrlp.vim'
" OPTIMIZATIONS - autoclosing, multicursor, sneak, :Bdelete, and surround
Plug 'Townk/vim-autoclose'
Plug 'terryma/vim-multiple-cursors'
Plug 'justinmk/vim-sneak'
Plug 'moll/vim-bbye'
Plug 'tpope/vim-surround'
" language support
Plug 'pangloss/vim-javascript' " javascript
Plug 'leafgarland/typescript-vim' " typescript
Plug 'digitaltoad/vim-pug' " pug
" THEME - ripped this off of the 'cool' theme that came with vim-airline lmao
Plug 'bclindner/vim-airline-bclindner'
call plug#end()
filetype plugin indent on
set omnifunc=syntaxcomplete#Complete
" end vim-plug configuration

" binds
"" NERDtree
map <C-t> :NERDTreeToggle<CR>
"" alt-movement between splits
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
"" tab movement between buffer
nmap <Tab> :bnext<CR>
nmap <S-Tab> :bprev<CR>
"" C-x closes buffer
nmap <C-x> :Bdelete<CR>
"" abbreviate to allow tag autoclosing - type </(space)
iabbrev <// </<C-X><C-O>
" end binds

" general options
"" colorscheme
colorscheme zellner
"" line options
set list
set listchars=tab:→\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨
set number
set linebreak
set showbreak=">>>"
"" QoL
set hidden
set visualbell
"" search options
set showmatch
set nohlsearch
set smartcase
set ignorecase
set incsearch
"" set indent options (default 2 spaces)
set autoindent
set shiftwidth=2
set expandtab
set smartindent
set softtabstop=2
"" use mouse, because sometimes i'm just lazy
set mouse=a
"" make backspace not stupid
set backspace=indent,eol,start
"" syntax highlighting
syntax enable
"" for makefiles and go files: use noexpandtab
autocmd FileType go set noexpandtab
autocmd FileType go set tabstop=2
autocmd FileType make set noexpandtab
autocmd FileType make set tabstop=2
" end general options

" plugin configuration
"" nerdtree stuff
autocmd StdinReadPre * let s:std_in=1
let g:NERDTreeWinPos = "right"
"" airline stuff
set laststatus=2
let g:airline_theme='bclindner'
""" enable bufferline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
""" set airline symbols
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = '☰'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = '∄'
let g:airline_symbols.whitespace = 'Ξ'
"" ctrlp stuff - ignore line
set wildignore+=node_modules
" end plugin configuration

" custom commands
command! Vimrc e $MYVIMRC
command! VimrcUpdate source $MYVIMRC
" end custom commands

