" bclindner vimrc

" plugins
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"" let Vundle self-update
Plugin 'VundleVim/Vundle.vim'
" statusline
Plugin 'vim-airline/vim-airline'
" git wrapper
Plugin 'tpope/vim-fugitive'
" file tree
Plugin 'scrooloose/nerdtree'
" async linter
Plugin 'w0rp/ale'
" sneak motion (replaces `s`)
Plugin 'justinmk/vim-sneak'
" custom theme
Plugin 'bclindner/vim-airline-bclindner'
" autoclosing capabilities
Plugin 'Townk/vim-autoclose'
" SublimeText-style multicursor
Plugin 'terryma/vim-multiple-cursors'
" language support
Plugin 'digitaltoad/vim-pug'
" close buffers w/o closing window
Plugin 'moll/vim-bbye'
" useful plugin for dealing w/ quotes
Plugin 'tpope/vim-surround'
" ctrl-p is nice
Plugin 'ctrlpvim/ctrlp.vim'
" good indent guides
Plugin 'Yggdroot/indentLine'
call vundle#end()
filetype plugin indent on

" binds
"" NERDtree
map <C-t> :NERDTreeToggle<CR>
"" alt-movement between splits
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
"" tab movement between buffer
nmap <Tab> :bnext<CR>
nmap <S-Tab> :bprev<CR>
"" C-x closes buffer
nmap <C-x> :Bdelete<CR>

" general options
colorscheme zellner
" line options
set hidden
set list
set listchars=tab:→\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨
set number
set linebreak
set showbreak=">>>"
set showmatch
set visualbell
"" search options
set nohlsearch
set smartcase
set ignorecase
set incsearch
"" set indent options (default 2 spaces)
set autoindent
set shiftwidth=2
set expandtab
set smartindent
set softtabstop=2
"" use mouse, because sometimes i'm just lazy
set mouse=a
"" make backspace not stupid
set backspace=indent,eol,start
"" syntax highlighting
syntax enable
"" for makefiles: use noexpandtab
autocmd FileType make set noexpandtab

" plugin configuration
"" nerdtree stuff
autocmd StdinReadPre * let s:std_in=1
"" airline stuff
set laststatus=2
let g:airline_theme='bclindner'
""" enable bufferline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
""" set airline symbols
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = '☰'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = '∄'
let g:airline_symbols.whitespace = 'Ξ'
"" ctrlp stuff - ignore line
set wildignore+=node_modules
